SELECT EMP_ID, EMP_NAME,
SALARY,
ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS ROW_NUM
FROM employees;

SELECT EMP_NAME, JOIN_DATE,
ROW_NUMBER() OVER(ORDER BY JOIN_DATE DESC) AS ROW_NUM
FROM employees;

SELECT EMP_NAME, SALARY,
ROW_NUMBER() OVER(ORDER BY SALARY ASC) AS ROW_NUM
FROM employees;

SELECT EMP_NAME, SALARY,
RANK() OVER(ORDER BY SALARY DESC) AS RANKING
FROM employees;

SELECT EMP_NAME, JOIN_DATE,
RANK() OVER(ORDER BY JOIN_DATE DESC) AS RANKING
FROM employees;

SELECT EMP_NAME, SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANKING
FROM employees;

SELECT EMP_NAME, JOIN_DATE,
DENSE_RANK() OVER(ORDER BY JOIN_DATE DESC) AS DENSE_RANKING
FROM employees;

SELECT ORDER_ID, ORDER_DATE,
ROW_NUMBER() OVER(ORDER BY ORDER_DATE DESC) AS ROW_NUM
FROM orders;

SELECT ORDER_ID, AMOUNT,
RANK() OVER(ORDER BY AMOUNT DESC) AS RANKING
FROM orders;

SELECT ORDER_ID, AMOUNT,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DENSE_RANKING
FROM orders;
